version: '3'

# assign a new common network and attach all services to it.
networks:
    test_network:
        external: true

services:
  python_web_app:
    build:
        context: ./web_app
        dockerfile: Dockerfile
    networks:
      - test_network
    ports:
      - "5000:5000"
    depends_on:
      - pg_image
    env_file:
      - "bin/env.sh"
    #command: bash -c "sleep 5 && python3 app.py"
    command: ["bin/wait_for_postgres.sh", "bash", "python3", "app.py"]

  pg_image:
    image: postgres:11.13-alpine
    networks:
      - test_network
    restart: always
    deploy:
      resources:
        limits:
          cpus: '1.500'
    volumes:
      - pg_db_data:/var/lib/postgresql/data
      # initialise DB schema and load given data into a table.
      - ./data/GlobalLandTemperaturesByCity.csv:/tmp/GlobalLandTemperaturesByCity.csv
      - ./sql/10_create_schema.sql:/docker-entrypoint-initdb.d/10_create_schema.sql
      - ./sql/20_load_data.sql:/docker-entrypoint-initdb.d/20_load_data.sql
    expose:
      - "5432"
    ports:
      - "5432:5432"
    env_file:
      - "bin/env.sh"

volumes:
    pg_db_data:

